// src/digitbox.tsx
"use client";

import type { FormEvent, FormEventHandler, ForwardedRef } from "react";
import { createRef, forwardRef, useEffect, useRef } from "react";
import { bindRef, ify } from "./utils";

type DigitboxProps = {
  formId?: string, label?: string, name?: string,
  digits: number, isNumeric?: boolean, disabled?: boolean
  className?: string, digitClass?: string,
  onInput?: FormEventHandler<HTMLInputElement>, 
  onChange?: FormEventHandler<HTMLInputElement>,
}

const Digitbox = forwardRef<HTMLInputElement, DigitboxProps>(({
  formId, label, digits, className, digitClass, isNumeric=true, onInput, onChange, disabled=false, name
}, ref: ForwardedRef<HTMLInputElement>) => {
  const digitboxes = useRef(Array.from({ length: digits }, () => createRef<HTMLInputElement>()));
  function updateDigits(e:FormEvent<HTMLInputElement>) {
    if(internalRef.current == null)
      return;
    internalRef.current.value = digitboxes.current.reduce((prev, curr) => prev+(curr.current?.value||' '), "");
    onInput && onInput(e);
  }
  const internalRef = useRef<HTMLInputElement>(null);
  useEffect(() => bindRef(ref, internalRef.current), [ref]);
  if(digits < digitboxes.current.length)
    digitboxes.current.length = digits;
  else if(digits > digitboxes.current.length)
    digitboxes.current.push(...Array.from({ length: digits-digitboxes.current.length }, () => createRef<HTMLInputElement>()));
  return (<div className={ify("flex gap-2 h-12",className)}> <input ref={internalRef} type="hidden" /> { digitboxes.current.map((subref, i, boxes) => (<>
    <input key={i} name={name} id={`${formId}-${label}`} ref={subref} type={isNumeric?"number":"text"} maxLength={1} className={ify("code-box",digitClass)} 
      onFocus={()=>subref.current!.value = ''} disabled={disabled}
      onInput={(i+1) == boxes.length? (e)=>{boxes[i].current?.blur();updateDigits(e);onChange&&onChange(e)} : (e)=>{boxes[i+1].current?.focus();updateDigits(e)}} />
  </>))} </div>);
})
Digitbox.displayName = 'Digitbox';
export default Digitbox;

// packages/svelte/src/Digitbox.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { ify, twId } from "./utils";

  export let formId: string | undefined = undefined;
  export let label: string | undefined = undefined;
  export let digits: number;
  export let isNumeric: boolean = true;
  export let disabled: boolean = false;
  export let className: string | undefined = undefined;
  export let digitClass: string | undefined = undefined;

  const dispatch = createEventDispatcher<{ input: Event & { currentTarget: HTMLInputElement }; change: Event & { currentTarget: HTMLInputElement } }>();
  const id = twId("digitbox", label, formId);

  let internalRef: HTMLInputElement;
  export { internalRef as ref };

  let digitEls: HTMLInputElement[] = [];
  $: if(digitEls.length !== digits) digitEls.length = digits;

  function updateDigits(e: Event & { currentTarget: HTMLInputElement }) {
    if(internalRef == null) return;
    internalRef.value = digitEls.reduce((prev, el) => prev + (el?.value || " "), "");
    dispatch("input", e);
  }
</script>

<div class={ify("flex gap-2 h-12", className)}>
  <input bind:this={internalRef} {id} type="hidden" />
  {#each Array.from({ length: digits }, (_, i) => i) as i (i)}
    <input bind:this={digitEls[i]} type={isNumeric ? "number" : "text"} maxlength={1} class={ify("code-box", digitClass)}
      on:focus={() => digitEls[i] && (digitEls[i].value = "")} {disabled}
      on:input={(i + 1) == digits ? (e) => { digitEls[i]?.blur(); updateDigits(e); dispatch("change", e); } : (e) => { digitEls[i + 1]?.focus(); updateDigits(e); }} />
  {/each}
</div>
