// packages/svelte/src/SmartGridView.svelte
<script lang="ts">
  import { untrack, type Snippet } from "svelte";
  import { ify } from "./utils";

  type SmartGridImg = [string, number, Snippet][];
  type SmartGridLayout = {
    columns: number, cols: string[][], heights: number[], placed: Set<string>
  };

  function shortestCol(heights: number[]) {
    let shortest = 0;
    for(let i = 1; i < heights.length; ++i)
      if(heights[i] < heights[shortest])
        shortest = i;
    return shortest;
  }

  function relayout(images: SmartGridImg, columns: number, prev: SmartGridLayout): SmartGridLayout {
    const kept = prev.columns === columns
      && images.reduce((count, [ key ]) => count + (prev.placed.has(key)? 1 : 0), 0) === prev.placed.size;
    const appended = kept? images.filter(([ key ]) => !prev.placed.has(key)) : images;
    if(kept && appended.length === 0)
      return prev;
    const layout: SmartGridLayout = kept? {
      columns, cols: prev.cols.map(col => col.slice()),
      heights: prev.heights.slice(), placed: new Set(prev.placed)
    } : {
      columns, cols: Array.from({ length: columns }, () => [] as string[]),
      heights: Array.from({ length: columns }, () => 0), placed: new Set<string>()
    };
    for(const [ key, ratio ] of appended) {
      const col = shortestCol(layout.heights);
      layout.cols[col].push(key);
      layout.heights[col] += ratio > 0? ratio : 1;
      layout.placed.add(key);
    }
    return layout;
  }

  let {
    images, className = undefined, innerClass = undefined, cardClass = undefined,
    template = undefined, columns = undefined, loading = false, threshold = 0, onScrollEnd = undefined
  }: {
    images: SmartGridImg;
    className?: string;
    innerClass?: string;
    cardClass?: string;
    template?: Snippet;
    columns?: number;
    loading?: boolean;
    threshold?: number;
    onScrollEnd?: () => void;
  } = $props();

  let gridEl = $state<HTMLDivElement | undefined>(undefined);
  let rowEl = $state<HTMLDivElement | undefined>(undefined);
  let sentinelEl = $state<HTMLDivElement | undefined>(undefined);
  let colCount = $state(untrack(() => columns && columns > 0? columns : 1));
  let prevLayout: SmartGridLayout = { columns: 0, cols: [], heights: [], placed: new Set<string>() };
  let loaded = 0;
  let pending = false;

  const layout = $derived(prevLayout = relayout(images, colCount, prevLayout));
  const cards = $derived(new Map(images.map(([ key, _ratio, image ]) => [ key, image ])));

  $effect(() => {
    if(columns && columns > 0) {
      colCount = columns;
      return;
    }
    const el = rowEl;
    if(el == null)
      return;
    const readCols = () => {
      const declared = parseInt(getComputedStyle(el).getPropertyValue("--tw-smart-grid-cols"));
      colCount = declared > 0? declared : 1;
    };
    readCols();
    const resized = new ResizeObserver(readCols);
    resized.observe(el);
    return () => resized.disconnect();
  });
  $effect(() => {
    const el = sentinelEl;
    const root = gridEl;
    if(el == null || root == null)
      return;
    if(loaded !== layout.placed.size) {
      loaded = layout.placed.size;
      pending = false;
    }
    const watcher = new IntersectionObserver(([ entry ]) => {
      if(!entry.isIntersecting) {
        pending = false;
        return;
      }
      if(pending)
        return;
      pending = true;
      onScrollEnd?.();
    }, { root, rootMargin: threshold+"px" });
    watcher.observe(el);
    return () => watcher.disconnect();
  });
</script>

<div bind:this={gridEl} class={ify("smart-grid-view", className)}>
  <div bind:this={rowEl} class="smart-grid-columns">
    {#each layout.cols as col, index (index)}
      <ul class={ify("smart-grid-column", innerClass)}>
        {#each col as key (key)}
          {@const card = cards.get(key)}
          <li class={ify("smart-grid-card", cardClass)}>{#if card}{@render card()}{/if}</li>
        {/each}
        {#if loading && template}
          <li aria-hidden="true" class={ify("smart-grid-card", cardClass)}>{@render template()}</li>
        {/if}
      </ul>
    {/each}
  </div>
  <div bind:this={sentinelEl} aria-hidden="true" class="smart-grid-sentinel"></div>
</div>

// packages/react/src/smart_grid_view.tsx
"use client";

import type { MutableRefObject, ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import { ify } from "./utils";

type SmartGridImg = { [key in string]: [ number, ReactNode ] };
type SmartGridLayout = {
  source: SmartGridImg | null, columns: number,
  cols: string[][], heights: number[], placed: Set<string>
};

function shortestCol(heights: number[]) {
  let shortest = 0;
  for(let i = 1; i < heights.length; ++i)
    if(heights[i] < heights[shortest])
      shortest = i;
  return shortest;
}

function relayout(images: SmartGridImg, columns: number, prev: SmartGridLayout): SmartGridLayout {
  const entries = Object.entries(images);
  const kept = prev.columns === columns
    && entries.reduce((count, [ key ]) => count + (prev.placed.has(key)? 1 : 0), 0) === prev.placed.size;
  const appended = kept? entries.filter(([ key ]) => !prev.placed.has(key)) : entries;
  if(kept && appended.length === 0)
    return { ...prev, source: images };
  const layout: SmartGridLayout = kept? {
    source: images, columns, cols: prev.cols.map(col => col.slice()),
    heights: prev.heights.slice(), placed: new Set(prev.placed)
  } : {
    source: images, columns, cols: Array.from({ length: columns }, () => [] as string[]),
    heights: Array.from({ length: columns }, () => 0), placed: new Set<string>()
  };
  for(const [ key, [ ratio ] ] of appended) {
    const col = shortestCol(layout.heights);
    layout.cols[col].push(key);
    layout.heights[col] += ratio > 0? ratio : 1;
    layout.placed.add(key);
  }
  return layout;
}

export default function SmartGridView({
  images, className, innerClass, cardClass, template, columns, loading, threshold = 0, onScrollEnd
} : {
  className?: string, innerClass?: string, cardClass?: string,
  images: SmartGridImg, template?: ReactNode,
  columns?: number, loading?: boolean, threshold?: number,
  onScrollEnd?: ()=>void
}) {
  const grid : MutableRefObject<HTMLDivElement|null> = useRef(null);
  const row : MutableRefObject<HTMLDivElement|null> = useRef(null);
  const sentinel : MutableRefObject<HTMLDivElement|null> = useRef(null);
  const scrollEnd : MutableRefObject<(()=>void)|undefined> = useRef(onScrollEnd);
  const pending = useRef(false);
  const [ colCount, setColCount ] = useState(columns && columns > 0? columns : 1);
  const [ layout, setLayout ] = useState<SmartGridLayout>(
    () => ({ source: null, columns: 0, cols: [], heights: [], placed: new Set<string>() })
  );

  if(layout.source !== images || layout.columns !== colCount)
    setLayout(relayout(images, colCount, layout));

  useEffect(() => { scrollEnd.current = onScrollEnd }, [onScrollEnd]);
  useEffect(() => {
    if(columns && columns > 0) {
      setColCount(columns);
      return;
    }
    const el = row.current;
    if(el == null)
      return;
    const readCols = () => {
      const declared = parseInt(getComputedStyle(el).getPropertyValue("--tw-smart-grid-cols"));
      setColCount(declared > 0? declared : 1);
    };
    readCols();
    const resized = new ResizeObserver(readCols);
    resized.observe(el);
    return () => resized.disconnect();
  }, [columns]);
  useEffect(() => {
    const el = sentinel.current;
    if(el == null || grid.current == null)
      return;
    pending.current = false;
    const watcher = new IntersectionObserver(([ entry ]) => {
      if(!entry.isIntersecting) {
        pending.current = false;
        return;
      }
      if(pending.current)
        return;
      pending.current = true;
      scrollEnd.current?.();
    }, { root: grid.current, rootMargin: threshold+"px" });
    watcher.observe(el);
    return () => watcher.disconnect();
  }, [layout.placed.size, threshold]);

  return (<div ref={grid} className={ify("smart-grid-view", className)}>
    <div ref={row} className="smart-grid-columns">
      { layout.cols.map((col, index) =>
        <ul key={index} className={ify("smart-grid-column", innerClass)}>
          { col.map(key => <li key={key} className={ify("smart-grid-card", cardClass)}>{ images[key]?.[1] }</li>) }
          { loading && template && <li aria-hidden className={ify("smart-grid-card", cardClass)}>{ template }</li> }
        </ul>
      )}
    </div>
    <div ref={sentinel} aria-hidden className="smart-grid-sentinel"></div>
  </div>);
}
