// packages/svelte/src/Toggle.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { ify, twId } from "./utils";

  export let formId: string | undefined = undefined;
  export let label: string | undefined = undefined;
  export let className: string | undefined = undefined;
  export let trackClass: string | undefined = undefined;
  export let thumbClass: string | undefined = undefined;
  export let ref: HTMLInputElement;

  const dispatch = createEventDispatcher<{ change: Event & { currentTarget: HTMLInputElement } }>();
  const id = twId("toggle", label, formId);
</script>

<div class={ify("layers toggle-base", className)}>
  <input bind:this={ref} {id} type="checkbox" class="peer ghost-node"
    on:change={(e) => (e.currentTarget.value = e.currentTarget.checked.toString()) && dispatch("change", e)} />
  <div class={ify("layer toggle-track", trackClass)}></div>
  <div class="layer toggle-thumb-wrapper"><div class={ify("toggle-thumb", thumbClass)}><slot /></div></div>
  <label for={id} class="layer cursor-pointer"></label>
</div>

// src/toggle.tsx
"use client";

import type { FormEventHandler, ForwardedRef, ReactNode } from "react";
import { forwardRef, useId } from "react";
import { ify } from "./utils";

type ToggleProps = {
  formId?: string, label?: string, children ?: ReactNode
  className?: string, trackClass?: string, thumbClass?: string,
  onChange?: FormEventHandler<HTMLInputElement>, name?: string
};

const Toggle = forwardRef<HTMLInputElement, ToggleProps>(({
  formId, label, className, trackClass, thumbClass, children, onChange, name
}, ref: ForwardedRef<HTMLInputElement>) => {
  const id = `${formId}-${label}-${useId()}`;
  return (<div className={ify("layers toggle-base",className)}>
    <input name={name} ref={ref} id={id} type="checkbox" className="peer ghost-node" 
      onChange={(e) => {e.target.value = e.target.checked.toString(); onChange && onChange(e)}} />
    <div className={ify("layer toggle-track",trackClass)}></div>
    <div className="layer toggle-thumb-wrapper"><div className={ify("toggle-thumb",thumbClass)}>{ children }</div></div>
    <label htmlFor={id} className="layer cursor-pointer"></label>
  </div>);
});
Toggle.displayName = "Toggle";
export default Toggle;
